name: Continuous Integration

on:
  pull_request:
    branches:
      - dev 
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    
    - name: Install node modules
      run: |
        yarn install
        
    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
          eslint: true
          prettier: true
        
    - name: bundle
      run: |
        yarn loadscript
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew
        
#     - name: Build Android App Bundle
#       run: |
#         cd android && ./gradlew assembleDebug
  
    - name: Build Android apk (debug)
#       run: ./gradlew assembleDebug -Dorg.gradle.logging.level=info
      run: ./gradlew assembleDebug
#         run: |
#           cd ./android && ./gradlew assembleDebug
      working-directory: android
    - name: Upload Artifact Debug
      uses: actions/upload-artifact@v2
      with:
          name: ${{ github.event.head_commit.message }}-debug
          path: '**/*.apk'
#           name: app-release.apk
#           path: android/app/build/outputs/apk/release/
    - name: Build Android ( Release ) 
      run: |
          cd android && ./gradlew assembleRelease
    - name: Upload Artifact Release Android
      uses: actions/upload-artifact@v2
      with:
          name: ${{ github.event.commits[0].message }}-release
          path: '**/*.apk'
#     - name: Upload APK
#       uses: actions/upload-artifact@v1
#       with:
#           name: app
#           path: '**/*.apk'
