name: Continuous Integration

on:
  pull_request:
    branches:
      - dev 
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    
    - name: Install node modules
      run: |
        yarn install
        
#     - name: Run linters
#       uses: wearerequired/lint-action@v1
#       with:
#           eslint: true
#           prettier: true
        
    - name: bundle
      run: |
        yarn loadscript
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew
        
    - name: Build Android App Bundle
      run: |
        cd android && ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
          name: app
          path: '**/*.apk'
