name: Continuous Integration

on:
  pull_request:
    branches:
      - dev 
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    
    - name: Run lint test
      run: |
        yarn test
          
    - name: Build Android App Bundle
      run: |
        cd android && ./gradlew assembleDebug
